version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000" # Adjust port as necessary
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306" # Adjust port as necessary
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
